=== KoV96/EpamJava-7/input.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs ="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.students.com"
           elementFormDefault="qualified">
    <xs:element name="Students">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Student" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                            <xs:element name="firstName" type="xs:string"/>
                            <xs:element name="lastName" type="xs:string"/>
                            <xs:element name="age">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="120"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        <xs:element name="country">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="USA"/>
                                    <xs:enumeration value="Ukraine"/>
                                    <xs:enumeration value="Poland"/>
                                    <xs:enumeration value="Columbia"/>
                                    <xs:enumeration value="France"/>
                                    <xs:enumeration value="Germany"/>
                                    <xs:enumeration value="Canada"/>
                                    <xs:enumeration value="Italy"/>
                                    <xs:enumeration value="Spain"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="phoneNumber" type="xs:long"/>
                        <xs:element name="params">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="height">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:double">
                                                <xs:minInclusive value="100.00"/>
                                                <xs:maxInclusive value="230.00"/>
                                            </xs:restriction>

                                        </xs:simpleType>
                                    </xs:element>
                                    <xs:element name="weight">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:double">
                                                <xs:minInclusive value="40.00"/>
                                                <xs:maxInclusive value="250.00"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                    <xs:element name="colour">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="black"/>
                                                <xs:enumeration value="white"/>
                                                <xs:enumeration value="yellow"/>
                                            </xs:restriction>

                                        </xs:simpleType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== KoV96/EpamJava-7/input.xml
<?xml version="1.0" encoding="UTF-8" ?>

<Students xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.students.com"
          xs:schemaLocation="http://www.students.com input.xsd">
    <Student>
        <firstName>Barack</firstName>
        <lastName>Obama</lastName>
        <age>18</age>
        <country>USA</country>
        <phoneNumber>03425234</phoneNumber>
        <params>
            <height>184.3</height>
            <weight>98.3</weight>
            <colour>black</colour>
        </params>
    </Student>
    <Student>
        <firstName>Jorge</firstName>
        <lastName>Bush</lastName>
        <age>22</age>
        <country>USA</country>
        <phoneNumber>03422222</phoneNumber>
        <params>
            <height>174.3</height>
            <weight>88.0</weight>
            <colour>white</colour>
        </params>
    </Student>
    <Student>
        <firstName>Pablo</firstName>
        <lastName>Escobar</lastName>
        <age>22</age>
        <country>Columbia</country>
        <phoneNumber>124324235</phoneNumber>
        <params>
            <height>180.2</height>
            <weight>99.0</weight>
            <colour>white</colour>
        </params>
    </Student>
    <Student>
        <firstName>Cathrine</firstName>
        <lastName>Smith</lastName>
        <age>20</age>
        <country>France</country>
        <phoneNumber>2332234</phoneNumber>
        <params>
            <height>160.3</height>
            <weight>55.0</weight>
            <colour>white</colour>
        </params>
    </Student>
    <Student>
        <firstName>Anna</firstName>
        <lastName>Kravchuk</lastName>
        <age>19</age>
        <country>Ukraine</country>
        <phoneNumber>05868383</phoneNumber>
        <params>
            <height>176.4</height>
            <weight>60.1</weight>
            <colour>white</colour>
        </params>
    </Student>
</Students>
